package com.mlongbo.jfinal.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_user", User.USER_ID, User.class);//用户表
		arp.addMapping("t_roles", Role.ROLE_ID, Role.class);//角色表
		arp.addMapping("t_userroles",UserRole.USER_ID, UserRole.class);//角色用户关联表
		arp.addMapping("t_permission", Permission.PERMISSION_ID, Permission.class);//权限表
		arp.addMapping("t_rolepermissions", RolePermissions.class);//权限角色关联表
        arp.addMapping("t_register_code", RegisterCode.MOBILE, RegisterCode.class); //注册验证码对象
        arp.addMapping("t_feedback", FeedBack.class); //意见反馈表
        arp.addMapping("product", Product.class); //商品表
        arp.addMapping("product_type", ProductType.class); //商品类型表
        arp.addMapping("sms_buy_log", SmsBuyLog.class); //短信购买记录
        arp.addMapping("sms_send_log", SmsSendLog.class); //短信使用记录
        arp.addMapping("sms_store", SmsStore.class); //短信库
        arp.addMapping("sms_template", SmsTemplate.class); //短信模板
        arp.addMapping("sms_buy_config", SmsBuyConfig.class); //短信购买模板
        arp.addMapping("session", "id", Session.class);
        arp.addMapping("orders", "orderId", Orders.class);//订单
	}
}

